foreground            #ecdfe5
background            #181215
selection_foreground  #fadaec
selection_background  #56404e
url_color             #f6b2df
cursor                #ecdfe5
cursor_text_color     #181215

# Tabs
active_tab_foreground   #ffd7ef
active_tab_background   #69355b
inactive_tab_foreground #d2c2ca
inactive_tab_background #201a1e

# Windows
active_border_color     #f6b2df
inactive_border_color   #9b8d94

# Terminal Colors (0-15)
color0  #181215
color8  #3f373b

color1  #ffb4ab
color9  #93000a

color2  #f6b2df
color10 #69355b

color3  #dcbed0
color11 #56404e

color4  #f5b9a1
color12 #663c2b

color5  #834c74
color13 #834c74

color6  #9b8d94
color14 #4f444a

color7  #ecdfe5
color15 #d2c2ca
